/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 30 черв 2011, 10:02:20
 */
package com.fairbg.gui;

import com.fairbg.core.Board;
import com.fairbg.core.Demiurge;
import com.fairbg.core.IBoardDisplay;
import com.fairbg.core.commands.Command;
import com.fairbg.core.commands.CommanderImpl;
import com.fairbg.core.commands.ICommandListener;
import java.awt.Graphics;
import sun.security.util.Debug;

/**
 *
 * @author Vitalik
 */
public class Main extends javax.swing.JFrame implements IBoardDisplay {

    /** Creates new form Main */
    public Main() {
        initComponents();
        _commander = new CommanderImpl(this);
        Demiurge.getCorel().setBoardDisplay(this);
        Demiurge.getCorel().startListenCommander();        
        setSize(480, 800);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //System.out.println("Try to stop listen Bluetooth commander");
        Demiurge.getCorel().stopListenCommander();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private CommanderImpl _commander = null;
    private Board _board = null;

    public void setBoardObject(Board board) {
        _board = board;
        updateDisplay();
    }

    public void updateDisplay() {
        repaint();
    }

    public void addListener(ICommandListener listener) {
        _commander.addListener(listener);
    }

    public void sendCommand(Command command) {
        _commander.sendCommand(command);
    }

    public void start() {
        //
    }

    public void stop() {
        //
    }

    @Override
    public void paint(Graphics g) {
        //super.paint(g);        
        //g.fillRect(10, 10, 100, 100);        
        BoardPainter.draw(g, _board);
    }

    public void recieveCommand(Command command) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

}
